name: API testing

on:
  workflow_dispatch:

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 19
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'


      # Step 4: Run API Tests
      - name: Run API Tests

        run: |
          mvn -q clean test -Dtest=**/APITests/*
